/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBot: typeof import('./src/components/ai/ChatBot.vue')['default']
    ClientRegistration: typeof import('./src/components/authorization/client_registration/ClientRegistration.vue')['default']
    DomainEvents: typeof import('./src/components/dispatch/message/DomainEvents.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JobDetails: typeof import('./src/components/dispatch/schedule/JobDetails.vue')['default']
    LocalUser: typeof import('./src/components/authorization/user/LocalUser.vue')['default']
    Oauth2User: typeof import('./src/components/authorization/user/Oauth2User.vue')['default']
    PortChecher: typeof import('./src/components/tools/PortChecher.vue')['default']
    ProcessDefinitions: typeof import('./src/components/flowable/ProcessDefinitions.vue')['default']
    ProcessInstances: typeof import('./src/components/flowable/ProcessInstances.vue')['default']
    ProcessTasks: typeof import('./src/components/flowable/ProcessTasks.vue')['default']
    RegisteredClient: typeof import('./src/components/authorization/client_registration/RegisteredClient.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
