/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClientRegistration: typeof import('./src/components/authorization/client_registration/ClientRegistration.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Job: typeof import('./src/components/dispatch/schedule/Job.vue')['default']
    JobDetails: typeof import('./src/components/dispatch/schedule/JobDetails.vue')['default']
    LocalUser: typeof import('./src/components/authorization/user/LocalUser.vue')['default']
    Oauth2User: typeof import('./src/components/authorization/user/Oauth2User.vue')['default']
    OauthUser: typeof import('./src/components/authorization/user/OauthUser.vue')['default']
    RegisteredClient: typeof import('./src/components/authorization/client_registration/RegisteredClient.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
