/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[[...notFound]]': RouteRecordInfo<'/[[...notFound]]', '/:notFound(.*)?', { notFound?: ParamValueZeroOrOne<true> }, { notFound?: ParamValueZeroOrOne<false> }>,
    '/ai': RouteRecordInfo<'/ai', '/ai', Record<never, never>, Record<never, never>>,
    '/authorization': RouteRecordInfo<'/authorization', '/authorization', Record<never, never>, Record<never, never>>,
    '/dispatch': RouteRecordInfo<'/dispatch', '/dispatch', Record<never, never>, Record<never, never>>,
    '/flowable': RouteRecordInfo<'/flowable', '/flowable', Record<never, never>, Record<never, never>>,
    '/tools': RouteRecordInfo<'/tools', '/tools', Record<never, never>, Record<never, never>>,
    '/yellow': RouteRecordInfo<'/yellow', '/yellow', Record<never, never>, Record<never, never>>,
  }
}
